[hooks]
# TODO(qix-): Change this to exclude the minimap-app crate and otherwise use --all
# TODO(qix-): once rust-lang/rust-clippy#9555 is resolved.
pre-commit = "cargo fmt --all -- --check && cargo clippy -p minimap-core -- -D clippy::all"

[logging]
verbose = true
